# Generated by Django 2.1.5 on 2019-01-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
