# Generated by Django 2.1.5 on 2019-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0004_auto_20190125_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('confirm_passwordd', models.CharField(max_length=20)),
            ],
        ),
    ]
