# Generated by Django 2.1.5 on 2019-01-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0005_restregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restregistration',
            name='confirm_passwordd',
        ),
    ]
