# Generated by Django 2.1.5 on 2019-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0006_remove_restregistration_confirm_passwordd'),
    ]

    operations = [
        migrations.AddField(
            model_name='restregistration',
            name='confirm_password',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
